server:
  port: 8081
spring:
  application:
    name: cloud-config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/      #服务注册中信地址
  instance:
    prefer-ip-address: true         #将IP注册到服务注册中心
