server:
  port: 9091
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yanglinfeng11111/springCloudConfig
          search-paths: '{application}' # 存储文件夹

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'