server:
  port: 9093
spring:
  application:
    name: cloud-provider
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/      #服务注册中信地址，含有BASIC认证的用户名和密码
  instance:
    prefer-ip-address: true         #将IP注册到服务注册中心


