spring:
  application:
    name: cloud-discovery   #服务名称,自定义
server:
  port: 8082             #指定该Eureka实例的端口
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/      #服务注册中信地址
  instance:
    prefer-ip-address: true         #将IP注册到服务注册中心
